services:
  - type: web
    name: pluxlicense
    runtime: python
    repo: https://github.com/IceCloudPlux/PluxLicense
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_render:app
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: EPAY_PID
        sync: false
      - key: EPAY_KEY
        sync: false
      - key: NOTIFY_URL
        sync: false
      - key: RETURN_URL
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pluxchest-db
          property: connectionString

  - type: postgresql
    name: pluxchest-db
    plan: free
    region: oregon